from aiogram import types

from loader import dp

commands = ["/start", "/help", "/language"]
keyboards = [
        "ℹ Umumiy ma'lumotlar",
        "ℹ Основная информация",
        "ℹ General information",
        "🏫 Tuzilma",
        "🏫 Структура",
        "🏫 Structure",
        "🌐 Institut ijtimoiy tarmoqlarda",
        "🌐 Институт в социальных сетях",
        "🌐 The institute is on social networks",
        "📋 Institut haqida",
        "📋 Об институте",
        "📋 About the institute",
        "🗺 Institut manzili",
        "🗺 Адрес института",
        "🗺 Institute address",
        "☎ Institut bilan aloqa",
        "☎ Связь с институтом",
        "☎ Contact with the institute",
        "🔝 Bosh menyu",
        "🔝 Главное меню",
        "🔝 Main menu",
        "Institut bosh binosi",
        "Главный корпус института",
        "The main building of the institute",
        "Oziq-ovqat mahsulotlari texnologiyasi fakulteti",
        "Факультет пищевых технологий",
        "Faculty of Food Technology",
        "Yoqilg‘i va organik birikmalar kimyoviy texnologiyasi fakulteti",
        "Факультет химической технологии топлива и органических соединений",
        "Faculty of Chemical Technology of Fuels and Organic Compounds",
        "Noorganik moddalar texnologiyasi fakulteti",
        "Факультет технологии неорганических веществ",
        "Faculty of Inorganic Substances Technology",
        "Menejment va kasb ta'limi fakulteti",
        "Факультет менеджмента и профессионального образования",
        "Faculty of Management and Vocational Education",
        "Vinochilik texnologiyasi va sanoat uzumchiligi fakulteti",
        "Факультет технологии вина и промышленного виноградарства",
        "Faculty of Wine Technology and Industrial Viticulture",
        "Rasmiy sayt",
        "Официальный сайт",
        "Official site",
        "Telegram",
        "Телеграм",
        "Xalqaro hamkorlik(Telegram)",
        "Международное сотрудничество (Телеграм)",
        "International cooperation (Telegram)",
        "Institut rahbariyati",
        "Руководство института",
        "Institute leadership",
        "Fakultetlar",
        "Факультеты",
        "Faculties",
        "Kafedralar",
        "Кафедры",
        "Chairs",
        "Bo‘limlar va markazlar",
        "Отделения и центры",
        "Departments and centres",
        "TKTI Shahrisabz filiali",
        "ТКТИ Шахрисабзский филиал",
        "Shakhrisabz branch of TCTI",
        "TKTI Yangiyer filiali",
        "ТКТИ Янгиерский филиал",
        "Yangiyer branch of TCTI",
        "TKTI qoshidagi akademik litsey",
        "Академический лицей при ТКТИ",
        "Academic lyceum under TCTI",
        "Yoshlar Ittifoqi",
        "Союз Молодежи",
        "Youth Union",
        "🔙 Orqaga",
        "🔙 Назад",
        "🔙 Back",
        "Menejment va kasb ta'limi fakulteti dekani",
        "Декан факультета менеджмента и профессионального образования",
        "Dean of the Faculty of Management and Vocational Education",
        "Menejment va kasb ta'limi fakulteti kafedralari",
        "Кафедры факультета менеджмента и профессионального образования",
        "Departments of the Faculty of Management and Vocational Education",
        "Noorganik moddalar kimyoviy texnologiyasi fakulteti dekani",
        "Декан факультета химической технологии неорганических веществ",
        "Dean of the Faculty of Chemical Technology of Inorganic Substances",
        "Noorganik moddalar kimyoviy texnologiyasi fakulteti kafedralari",
        "Кафедры факультета химической технологии неорганических веществ",
        "Departments of the Faculty of Chemical Technology of Inorganic Substances",
        "Oziq-ovqat mahsulotlari texnologiyasi fakulteti dekani",
        "Декан факультета пищевых технологий",
        "Dean of the Faculty of Food Technology",
        "Oziq-ovqat mahsulotlari texnologiyasi fakulteti kafedralari",
        "Кафедры факультета пищевых технологий",
        "Departments of the Faculty of Food Technology",
        "Vinochilik texnologiyasi va sanoat uzumchiligi fakulteti dekani",
        "Декан факультета технологии вина и промышленного виноградарства",
        "Dean of the Faculty of Wine Technology and Industrial Viticulture",
        "Vinochilik texnologiyasi va sanoat uzumchiligi fakulteti kafedralari",
        "Кафедры факультета технологии вина и промышленного виноградарства",
        "Departments of the Faculty of Wine Technology and Industrial Viticulture",
        "Yoqilg‘i va organik birikmalar kimyoviy texnologiyasi fakulteti dekani",
        "Декан факультета химической технологии топлив и органических соединений",
        "Dean of the Faculty of Chemical Technology of Fuels and Organic Compounds",
        "Yoqilg‘i va organik birikmalar kimyoviy texnologiyasi fakulteti kafedralari",
        "Кафедры химической технологии топлив и органических соединений",
        "Departments of the Faculty of Chemical Technology of Fuels and Organic Compounds",
        "Shahrisabz filiali direktori",
        "Директор Шахрисабзского филиала",
        "Shahrisabz branch director",
        "Yangiyer filiali direktori",
        "Директор Янгиерского филиала",
        "Yangiyer branch director",
        "Rektor",
        "Ректор",
        "Rector",
        "O‘quv ishlari bo‘yicha prorektor",
        "Проректор по учебной работе",
        "Vice Rector for Academic Affairs",
        "Ilmiy ishlar va innovatsiyalar bo‘yicha prorektor",
        "Проректор по исследованиям и инновациям",
        "Vice Rector for Research and Innovation",
        "Yoshlar bilan ishlash bo‘yicha prorektor",
        "Проректор по делам молодежи",
        "Vice Rector for Youth Affairs",
        "Ishlar boshqarmasi boshlig‘i",
        "Начальник штаба",
        "Chief of Staff",
        "Devonxona va arxiv bo‘limi",
        "Отдел канцелярия и архив",
        "Chancellery and Archives Department",
        "Marketing bo‘limi",
        "Отдел маркетинга",
        "Marketing Department",
        "Kadrlar bo‘limi",
        "Отдел кадров",
        "Personnel Department",
        "Monitoring va ichki nazorat bo‘limi",
        "Отдел мониторинга и внутреннего контроля",
        "Monitoring and Internal Control Department",
        "Buxgalteriya bo‘limi",
        "Отдел бухгалтерии",
        "Accounting Department",
        "Reja-moliya bo‘limi",
        "Отдел планирования и финансов",
        "Planning and Finance Department",
        "Xalqaro aloqalar bo‘limi",
        "Отдел международные отношения",
        "Department of International Relations",
        "O‘quv-uslubiy bo‘lim",
        "Учебно-методический отдел",
        "Educational-methodical Department",
        "Ta'lim sifatini nazorat qilish bo‘limi",
        "Отдел контроля качества образования",
        "Education quality control Department",
        "Yoshlar bilan ishlash, ma'naviyat va ma'rifat bo‘limi",
        "Отдел по делам молодежи, духовности и просвещения",
        "Department of Youth Affairs, Spirituality and Education",
        "Magistratura bo‘limi",
        "Отдел магистратуры",
        "Department of Magistracy",
        "Axborot texnologiyalari markazi",
        "Центр информационных технологий",
        "Information Technology Centre",
        "Axborot-resurs markazi",
        "Информационно-ресурсный центр",
        "Information Resource Centre",
        "Sirtqi bo‘lim",
        "Заочный отделение",
        "Correspondence Department",
        "TKTI huzuridagi “Pedagogik kadrlani qayta tayyorlash va malaka oshirish” tarmoq markazi",
        "Сетевой центр «Переподготовка и повышение квалификации педагогических кадров» при ТКТИ",
        "Network center “Retraining and advanced training of teaching staff” at TCTI",
        "Yoshlar Ittifoqi yetakchisi",
        "Лидер Союза молодежи",
        "Leader of the Youth Union"
    ]


@dp.message_handler(content_types=types.ContentTypes.ANY)
async def other(message: types.Message):
    if message.text != commands or keyboards:
        await message.reply(
                text=f"<b>🇺🇿 Botdan foydalanish uchun /start yoki /help buyruqlaridan foydalaning.\n"
                     f"Buyruqlarni “Menyu” orqali ham ko‘rishingiz mumkin.\n"
                     f"Tilni o‘zgartirish uchun /language buyrug‘ini kiriting.\n\n"
                     f"🇷🇺 Используйте команды /start или /help для использования бота.\n"
                     f"Вы также можете просматривать команды через “Меню”.\n"
                     f"Введите команду /language, чтобы изменить язык.\n\n"
                     f"🇬🇧 Use the /start or /help commands to use the bot.\n"
                     f"You can also view the commands through the “Menu”.\n"
                     f"Enter the /language command to change the language.</b>"
        )
