from aiogram import types

uz_keyboard_address = types.InlineKeyboardMarkup(row_width=3)
uz_keyboard_address.add(types.InlineKeyboardButton(text="Institut bosh binosi", url="http://bit.ly/tctimap"))
uz_keyboard_address.add(types.InlineKeyboardButton(text="Oziq-ovqat mahsulotlari texnologiyasi fakulteti", url="http://bit.ly/tcti_oomtf"))
uz_keyboard_address.add(types.InlineKeyboardButton(text="Yoqilg‘i va organik birikmalar kimyoviy texnologiyasi fakulteti", url="http://bit.ly/tcti_yoobktf"))
uz_keyboard_address.add(types.InlineKeyboardButton(text="Noorganik moddalar texnologiyasi fakulteti", url="https://bit.ly/tcti_nmktf"))
uz_keyboard_address.add(types.InlineKeyboardButton(text="Menejment va kasb ta'limi fakulteti", url="http://bit.ly/tcti_mktf"))
uz_keyboard_address.add(types.InlineKeyboardButton(text="Vinochilik texnologiyasi va sanoat uzumchiligi fakulteti", url="https://www.maps.google.com/"))

ru_keyboard_address = types.InlineKeyboardMarkup(row_width=3)
ru_keyboard_address.add(types.InlineKeyboardButton(text="Главный корпус института", url="http://bit.ly/tctimap"))
ru_keyboard_address.add(types.InlineKeyboardButton(text="Факультет пищевых технологий", url="http://bit.ly/tcti_oomtf"))
ru_keyboard_address.add(types.InlineKeyboardButton(text="Факультет химической технологии топлива и органических соединений", url="http://bit.ly/tcti_yoobktf"))
ru_keyboard_address.add(types.InlineKeyboardButton(text="Факультет технологии неорганических веществ", url="https://bit.ly/tcti_nmktf"))
ru_keyboard_address.add(types.InlineKeyboardButton(text="Факультет менеджмента и профессионального образования", url="http://bit.ly/tcti_mktf"))
ru_keyboard_address.add(types.InlineKeyboardButton(text="Факультет технологии вина и промышленного виноградарства", url="https://www.maps.google.com/"))

en_keyboard_address = types.InlineKeyboardMarkup(row_width=3)
en_keyboard_address.add(types.InlineKeyboardButton(text="The main building of the institute", url="http://bit.ly/tctimap"))
en_keyboard_address.add(types.InlineKeyboardButton(text="Faculty of Food Technology", url="http://bit.ly/tcti_oomtf"))
en_keyboard_address.add(types.InlineKeyboardButton(text="Faculty of Chemical Technology of Fuels and Organic Compounds", url="http://bit.ly/tcti_yoobktf"))
en_keyboard_address.add(types.InlineKeyboardButton(text="Faculty of Inorganic Substances Technology", url="https://bit.ly/tcti_nmktf"))
en_keyboard_address.add(types.InlineKeyboardButton(text="Faculty of Management and Vocational Education", url="http://bit.ly/tcti_mktf"))
en_keyboard_address.add(types.InlineKeyboardButton(text="Faculty of Wine Technology and Industrial Viticulture", url="https://www.maps.google.com/"))