from .buttons import uz_keyboard, ru_keyboard, en_keyboard
from .general_keyboards import uz_keyboard_general, ru_keyboard_general, en_keyboard_general, uz_keyboard_address, ru_keyboard_address, en_keyboard_address
from .socialnetwork_keyboards import uz_keyboard_social, ru_keyboard_social, en_keyboard_social, keyboard_social_2
from .structure_keyboards import uz_keyboard_structure, ru_keyboard_structure, en_keyboard_structure, uz_keyboard_section, ru_keyboard_section, en_keyboard_section, uz_keyboard_yobktf, ru_keyboard_yobktf, en_keyboard_yobktf, uz_keyboard_mktf, ru_keyboard_mktf, en_keyboard_mktf, uz_keyboard_nmktf, ru_keyboard_nmktf, en_keyboard_nmktf, uz_keyboard_leadership, ru_keyboard_leadership, en_keyboard_leadership, uz_keyboard_oomtf, ru_keyboard_oomtf, en_keyboard_oomtf, uz_keyboard_faculty, ru_keyboard_faculty, en_keyboard_faculty, uz_keyboard_vtsuf, ru_keyboard_vtsuf, en_keyboard_vtsuf, uz_keyboard_filial_sh, ru_keyboard_filial_sh, en_keyboard_filial_sh, uz_keyboard_filial_y, ru_keyboard_filial_y, en_keyboard_filial_y, uz_keyboard_union, ru_keyboard_union, en_keyboard_union
from .language_buttons import language_keyboard

__all__ = [
    'uz_keyboard',
    'ru_keyboard',
    'en_keyboard',
    'uz_keyboard_general',
    'ru_keyboard_general',
    'en_keyboard_general',
    'uz_keyboard_address',
    'ru_keyboard_address',
    'en_keyboard_address',
    'uz_keyboard_social',
    'ru_keyboard_social',
    'en_keyboard_social',
    'keyboard_social_2',
    'uz_keyboard_vtsuf',
    'ru_keyboard_vtsuf',
    'en_keyboard_vtsuf',
    'uz_keyboard_faculty',
    'ru_keyboard_faculty',
    'en_keyboard_faculty',
    'uz_keyboard_oomtf',
    'ru_keyboard_oomtf',
    'en_keyboard_oomtf',
    'uz_keyboard_leadership',
    'ru_keyboard_leadership',
    'en_keyboard_leadership',
    'uz_keyboard_section',
    'ru_keyboard_section',
    'en_keyboard_section',
    'uz_keyboard_nmktf',
    'ru_keyboard_nmktf',
    'en_keyboard_nmktf',
    'uz_keyboard_mktf',
    'ru_keyboard_mktf',
    'en_keyboard_mktf',
    'uz_keyboard_yobktf',
    'ru_keyboard_yobktf',
    'en_keyboard_yobktf',
    'uz_keyboard_structure',
    'ru_keyboard_structure',
    'en_keyboard_structure',
    'uz_keyboard_filial_sh',
    'ru_keyboard_filial_sh',
    'en_keyboard_filial_sh',
    'uz_keyboard_filial_y',
    'ru_keyboard_filial_y',
    'en_keyboard_filial_y',
    'uz_keyboard_union',
    'ru_keyboard_union',
    'en_keyboard_union',
    'language_keyboard'
]
