from aiogram import types

uz_keyboard_section = types.ReplyKeyboardMarkup(row_width=2, one_time_keyboard=True, resize_keyboard=True)
uz_keyboard_section.add("Devonxona va arxiv bo‘limi")
uz_keyboard_section.row("Marketing bo‘limi", "Kadrlar bo‘limi")
uz_keyboard_section.add("Monitoring va ichki nazorat bo‘limi")
uz_keyboard_section.row("Buxgalteriya bo‘limi", "Reja-moliya bo‘limi")
uz_keyboard_section.add("Xalqaro aloqalar bo‘limi")
uz_keyboard_section.row("O‘quv-uslubiy bo‘lim", "Ta'lim sifatini nazorat qilish bo‘limi")
uz_keyboard_section.add("Yoshlar bilan ishlash, ma'naviyat va ma'rifat bo‘limi")
uz_keyboard_section.row("Magistratura bo‘limi", "Sirtqi bo‘lim")
uz_keyboard_section.row("Axborot texnologiyalari markazi", "Axborot-resurs markazi")
uz_keyboard_section.add("TKTI huzuridagi “Pedagogik kadrlani qayta tayyorlash va malaka oshirish” tarmoq markazi")
uz_keyboard_section.row("🔙 Orqaga", "🔝 Bosh menyu")

ru_keyboard_section = types.ReplyKeyboardMarkup(row_width=2, one_time_keyboard=True, resize_keyboard=True)
ru_keyboard_section.add("Отдел канцелярия и архив")
ru_keyboard_section.row("Отдел маркетинга", "Отдел кадров")
ru_keyboard_section.add("Отдел мониторинга и внутреннего контроля")
ru_keyboard_section.row("Отдел бухгалтерии", "Отдел планирования и финансов")
ru_keyboard_section.add("Отдел международные отношения")
ru_keyboard_section.row("Учебно-методический отдел", "Отдел контроля качества образования")
ru_keyboard_section.add("Отдел по делам молодежи, духовности и просвещения")
ru_keyboard_section.row("Отдел магистратуры", "Заочный отделение")
ru_keyboard_section.row("Центр информационных технологий", "Информационно-ресурсный центр")
ru_keyboard_section.add("Сетевой центр «Переподготовка и повышение квалификации педагогических кадров» при ТКТИ")
ru_keyboard_section.row("🔙 Назад", "🔝 Главное меню")

en_keyboard_section = types.ReplyKeyboardMarkup(row_width=2, one_time_keyboard=True, resize_keyboard=True)
en_keyboard_section.add("Chancellery and Archives Department")
en_keyboard_section.row("Marketing Department", "Personnel Department")
en_keyboard_section.add("Monitoring and Internal Control Department")
en_keyboard_section.row("Accounting Department", "Planning and Finance Department")
en_keyboard_section.add("Department of International Relations")
en_keyboard_section.row("Educational-methodical Department", "Education quality control Department")
en_keyboard_section.add("Department of Youth Affairs, Spirituality and Education")
en_keyboard_section.row("Department of Magistracy", "Correspondence Department")
en_keyboard_section.row("Information Technology Centre", "Information Resource Centre")
en_keyboard_section.add("Network center “Retraining and advanced training of teaching staff” at TCTI")
en_keyboard_section.row("🔙 Back", "🔝 Main menu")
